#!/bin/bash

# First argument: directory comtaining compiled solution and Antlr .jar file (if you are using the Java skeleton)
# If you are using a language other than Java you may wish to ignore this argument.

# Second argument: the .c program to be analysed

DIR=$1

OUTPUT=$(timeout --signal=9 25 java -cp ${DIR}:${DIR}/antlr-4.5.1-complete.jar:${DIR}/libs/commons-cli-1.3.1.jar tool.SRTool -f $2 &)
OUTPUT_LU=$(timeout --signal=9 120 java -cp ${DIR}:${DIR}/antlr-4.5.1-complete.jar:${DIR}/libs/commons-cli-1.3.1.jar tool.SRTool -f $2 -lu &)
OUTPUT_FUZZ=$(timeout --signal=9 25 java -cp ${DIR}:${DIR}/antlr-4.5.1-complete.jar:${DIR}/libs/commons-cli-1.3.1.jar tool.SRTool -f $2 -z &)
wait

if [ "$OUTPUT_FUZZ" == "INCORRECT" ]; then
    echo "INCORRECT"
    exit 0;
fi

checkValidOutput() {
    if [ "$1" == "CORRECT" ] || [ "$1" == "INCORRECT" ] || [ "$1" == "UNKNOWN" ]; then
      echo 1;
    else
      echo 0;
    fi
}

VALID_OUTPUT=$(checkValidOutput $OUTPUT)
VALID_OUTPUT_LU=$(checkValidOutput $OUTPUT_LU)

if [ "$OUTPUT_LU" == "CORRECT" ]; then
    echo "CORRECT";
    exit 0;
elif [ "$OUTPUT" == "CORRECT" ]; then
    echo "CORRECT";
    exit 0;
fi

if [ $VALID_OUTPUT -ne 1 ] || [ $VALID_OUTPUT_LU -ne 1 ]; then
    echo "UNKNOWN";
    exit 0;
fi

if [ "$OUTPUT" == "$OUTPUT_LU" ]; then
    echo $OUTPUT;
else
    echo "UNKNOWN";
fi
