#!/bin/bash

# First argument: directory comtaining compiled solution and Antlr .jar file (if you are using the Java skeleton)
# If you are using a language other than Java you may wish to ignore this argument.

# Second argument: the .c program to be analysed

DIR=$1

OUTPUT=$(timeout --signal=9 175 java -cp ${DIR}:${DIR}/antlr-4.5.1-complete.jar:${DIR}/libs/commons-cli-1.3.1.jar tool.SRTool -f $2 &)
OUTPUT_LU=$(timeout --signal=9 175 java -cp ${DIR}:${DIR}/antlr-4.5.1-complete.jar:${DIR}/libs/commons-cli-1.3.1.jar tool.SRTool -f $2 -lu &)
OUTPUT_FUZZ=$(timeout --signal=9 175 java -cp ${DIR}:${DIR}/antlr-4.5.1-complete.jar:${DIR}/libs/commons-cli-1.3.1.jar tool.SRTool -f $2 -z &)

wait
if [ "$OUTPUT_FUZZ" == "INCORRECT" ]; then
    echo "INCORRECT" 
elif [ "$OUTPUT" == "$OUTPUT_LU" ]; then
    echo $OUTPUT;
elif [ "$OUTPUT_LU" == "CORRECT" ]; then
    echo "CORRECT";
elif [ "$OUTPUT" == "CORRECT" ]; then
    echo "CORRECT";
elif [ "$OUTPUT" == "" ] || [ "$OUTPUT_LU" == "" ]; then
    echo "UNKNOWN";
else
    echo "UNKNOWN";
fi
