#!/bin/bash

# First argument: directory comtaining compiled solution and Antlr .jar file (if you are using the Java skeleton)
# If you are using a language other than Java you may wish to ignore this argument.

# Second argument: the .c program to be analysed

DIR=$1

OUTPUT=$(java -cp ${DIR}:${DIR}/antlr-4.5.1-complete.jar:${DIR}/libs/commons-cli-1.3.1.jar tool.SRTool -f $2 &)
OUTPUT_LU=$(java -cp ${DIR}:${DIR}/antlr-4.5.1-complete.jar:${DIR}/libs/commons-cli-1.3.1.jar tool.SRTool -f $2 -lu &)
wait

if [ "$OUTPUT" == "$OUTPUT_LU" ]; then
    echo $OUTPUT;
elif [ "$OUTPUT_LU" == "INCORRECT" ]; then
    echo $OUTPUT_LU;
else
    echo "UNKNOWN";
fi
